import js from "@eslint/js";

export default [
  js.configs.recommended,
  {
    ignores: ["app/static/vendor/**"],
  },
  {
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "script",
      globals: {
        window: "readonly",
        document: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        fetch: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        location: "readonly",
        history: "readonly",
        self: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        confirm: "readonly",
        alert: "readonly",
        requestAnimationFrame: "readonly",
        matchMedia: "readonly",
        IntersectionObserver: "readonly",
        MutationObserver: "readonly",
        CustomEvent: "readonly",
        HTMLElement: "readonly",
        HTMLStyleElement: "readonly",
        Element: "readonly",
        Event: "readonly",
        Document: "readonly",
        ShadowRoot: "readonly",
        SVGElement: "readonly",
        MathMLElement: "readonly",
        customElements: "readonly",
        Vue: "readonly",
        VueRouter: "readonly",
        admiral: "readonly",
        __: "readonly",
        apiUrl: "readonly",
        csrfToken: "readonly",
        bffFetch: "readonly",
        buildPagedUrl: "readonly",
        normalizePagedData: "readonly",
        _durationSecondsFromJob: "readonly",
        _progressPercentFromJob: "readonly",
        formatBytes: "readonly",
        formatTimestamp: "readonly",
        formatDuration: "readonly",
        formatRelativeTime: "readonly",
        normalizeStatus: "readonly",
        instanceStatusClass: "readonly",
        nodeStatusClass: "readonly",
        jobStatusClass: "readonly",
        backupStatusClass: "readonly",
        healthStatusClass: "readonly",
        showToast: "readonly",
        provisionResultStorageKey: "readonly",
        mergeProvisionCredentials: "readonly",
        normalizeProvisionCredentials: "readonly",
        storeProvisionResultSnapshot: "readonly",
        InstanceCreateView: "readonly",
        parseProvisionResultSnapshot: "readonly",
        LoginView: "readonly",
        DashboardView: "readonly",
        NodesView: "readonly",
        NodeDetailView: "readonly",
        CatalogAppsView: "readonly",
        CatalogAppFormView: "readonly",
        CatalogAppDetailView: "readonly",
        InstancesView: "readonly",
        InstanceProvisionedView: "readonly",
        InstanceDetailView: "readonly",
        InstanceRestoreView: "readonly",
        BackupsView: "readonly",
        BackupSettingsView: "readonly",
        BackupDetailView: "readonly",
        JobsView: "readonly",
        JobDetailView: "readonly",
        ChangePasswordView: "readonly",
        ChangePasswordStandaloneView: "readonly",
        routes: "readonly",
        router: "readonly",
        app: "readonly",
        describe: "readonly",
        it: "readonly",
        beforeEach: "readonly",
        afterEach: "readonly",
        require: "readonly",
        module: "readonly",
        __dirname: "readonly",
        process: "readonly",
        global: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      "no-console": "off",
      semi: ["warn", "always"],
      quotes: ["warn", "single"],
      "no-empty": "warn",
    },
  },
  {
    files: ["app/static/js/app.js"],
    rules: {
      "no-redeclare": "off",
    },
  },
];
