import js from "@eslint/js";

export default [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "script",
      globals: {
        window: "readonly",
        document: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        fetch: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        location: "readonly",
        URL: "readonly",
        confirm: "readonly",
        alert: "readonly",
        Vue: "readonly",
        VueRouter: "readonly",
        admiral: "readonly",
        __: "readonly",
        apiUrl: "readonly",
        csrfToken: "readonly",
        bffFetch: "readonly",
        formatBytes: "readonly",
        formatTimestamp: "readonly",
        formatDuration: "readonly",
        formatRelativeTime: "readonly",
        normalizeStatus: "readonly",
        instanceStatusClass: "readonly",
        nodeStatusClass: "readonly",
        jobStatusClass: "readonly",
        backupStatusClass: "readonly",
        healthStatusClass: "readonly",
        _durationSecondsFromJob: "readonly",
        _progressPercentFromJob: "readonly",
        buildPagedUrl: "readonly",
        normalizePagedData: "readonly",
        describe: "readonly",
        it: "readonly",
        beforeEach: "readonly",
        afterEach: "readonly",
        require: "readonly",
        module: "readonly",
        __dirname: "readonly",
        process: "readonly",
        global: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      "no-console": "off",
      semi: ["warn", "always"],
      quotes: ["warn", "single"],
      "no-empty": "warn",
    },
  },
];
