[build-system]
requires = ["flit_core>=3.8"]
build-backend = "flit_core.buildapi"

[project]
name = "admiral-flagship"
version = "0.0.1beta16"
description = "Admiral administrative web console"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.0",
    "gunicorn>=23.0",
    "requests>=2.31",
]

[tool.flit.module]
name = "app"

[tool.black]
line-length = 120
target-version = ["py311"]

[tool.ruff]
line-length = 120
target-version = "py311"
